--- 
abstract: Filtering HTML for Japanese cellphone
author: 
  - Naoki Tomita <tomita@cpan.org>
build_requires: 
  Encode::JP::Mobile: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-View-MobileJpFilter
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Plugin::MobileAgent: 0
  Catalyst::Runtime: 5.70
  Data::Visitor::Callback: 0
  HTML::MobileJp::Filter: 0
version: 0.01
